---
name: Checks (lint, format, type check)
on:
  pull_request:
  push:
    branches:
      - devel
      - main
      - 'stable**'
      - 'release**'
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867 # v7
      - name: Run checks
        run: uv run poe lint
      - name: Run formatter
        run: uv run poe format

